# Makefile.in generated by automake 1.10.1 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
# 2003, 2004, 2005, 2006, 2007, 2008  Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.






pkgdatadir = $(datadir)/conquest
pkglibdir = $(libdir)/conquest
pkgincludedir = $(includedir)/conquest
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = x86_64-unknown-linux-gnu
host_triplet = x86_64-unknown-linux-gnu
target_triplet = x86_64-unknown-linux-gnu
#bin_PROGRAMS = conquest$(EXEEXT) \
#	conqoper$(EXEEXT) \
#	conqai$(EXEEXT) \
#	conqstrat$(EXEEXT) \
#	conquestd$(EXEEXT) \
#	conqmetad$(EXEEXT) \
#	conqinit$(EXEEXT)
bin_PROGRAMS = conquestgl$(EXEEXT) \
	conquest$(EXEEXT) \
	conqoper$(EXEEXT) \
	conqai$(EXEEXT) \
	conqstrat$(EXEEXT) \
	conquestd$(EXEEXT) \
	conqmetad$(EXEEXT) \
	conqinit$(EXEEXT)
#bin_PROGRAMS = conquestgl$(EXEEXT)
libexec_PROGRAMS = conqdriv$(EXEEXT)
subdir = .
DIST_COMMON = README $(am__configure_deps) $(srcdir)/Makefile.am \
	$(srcdir)/Makefile.in $(srcdir)/config.h.in \
	$(top_srcdir)/configure INSTALL TODO config.guess config.sub \
	conqinit-lex.c conqinit-yacc.c conqinit-yacc.h conqstrat-lex.c \
	conqstrat-yacc.c conqstrat-yacc.h depcomp install-sh ltmain.sh \
	missing mkinstalldirs ylwrap
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/m4/libtool.m4 \
	$(top_srcdir)/m4/sdl.m4 $(top_srcdir)/acinclude.m4 \
	$(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
CONFIG_HEADER = config.h
CONFIG_CLEAN_FILES =
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = `echo $$p | sed -e 's|^.*/||'`;
am__installdirs = "$(DESTDIR)$(libdir)" "$(DESTDIR)$(bindir)" \
	"$(DESTDIR)$(libexecdir)" "$(DESTDIR)$(man6dir)" \
	"$(DESTDIR)$(sysconfdir)"
libLTLIBRARIES_INSTALL = $(INSTALL)
LTLIBRARIES = $(lib_LTLIBRARIES)
libUi_la_LIBADD =
am_libUi_la_OBJECTS = uimisc.lo
libUi_la_OBJECTS = $(am_libUi_la_OBJECTS)
libUi_la_LINK = $(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(libUi_la_LDFLAGS) \
	$(LDFLAGS) -o $@
#am_libUi_la_rpath = -rpath $(libdir)
am_libUi_la_rpath = -rpath $(libdir)
#am_libUi_la_rpath = -rpath $(libdir)
libUiCU_la_LIBADD =
am_libUiCU_la_OBJECTS = display.lo cprintf.lo colorCU.lo cd2lb.lo \
	iolb.lo cumisc.lo cuclient.lo options.lo clntauth.lo
libUiCU_la_OBJECTS = $(am_libUiCU_la_OBJECTS)
libUiCU_la_LINK = $(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(libUiCU_la_LDFLAGS) $(LDFLAGS) -o $@
#am_libUiCU_la_rpath = -rpath $(libdir)
libUiGL_la_LIBADD =
am_libUiGL_la_OBJECTS = GL.lo texfont.lo glfont.lo glmisc.lo \
	nConsvr.lo nMeta.lo prm.lo nAuth.lo nWelcome.lo nMenu.lo \
	nPlay.lo nCP.lo nDead.lo nCPHelp.lo nShipl.lo node.lo \
	nPlanetl.lo nTeaml.lo nUserl.lo nHistl.lo glcprintf.lo \
	gldisplay.lo render.lo nPlayBMenu.lo nPlayB.lo nPlayBHelp.lo \
	nOptions.lo colorGL.lo anim.lo hud.lo blinker.lo
libUiGL_la_OBJECTS = $(am_libUiGL_la_OBJECTS)
libUiGL_la_LINK = $(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(libUiGL_la_LDFLAGS) $(LDFLAGS) -o $@
am_libUiGL_la_rpath = -rpath $(libdir)
#am_libUiGL_la_rpath = -rpath $(libdir)
libconqclnt_la_LIBADD =
am_libconqclnt_la_OBJECTS = client.lo clientlb.lo playback.lo
libconqclnt_la_OBJECTS = $(am_libconqclnt_la_OBJECTS)
libconqclnt_la_LINK = $(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(libconqclnt_la_LDFLAGS) $(LDFLAGS) -o $@
#am_libconqclnt_la_rpath = -rpath \
#	$(libdir)
am_libconqclnt_la_rpath = -rpath \
	$(libdir)
#am_libconqclnt_la_rpath = -rpath $(libdir)
libconqinit_la_LIBADD =
am_libconqinit_la_OBJECTS = conqinit-yacc.lo conqinit-lex.lo \
	planinit.lo
libconqinit_la_OBJECTS = $(am_libconqinit_la_OBJECTS)
libconqinit_la_LINK = $(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(libconqinit_la_LDFLAGS) $(LDFLAGS) -o $@
#am_libconqinit_la_rpath = -rpath \
#	$(libdir)
am_libconqinit_la_rpath = -rpath \
	$(libdir)
#am_libconqinit_la_rpath = -rpath $(libdir)
libconqserv_la_LIBADD =
am_libconqserv_la_OBJECTS = servauth.lo server.lo serverpkt.lo \
	servercmd.lo
libconqserv_la_OBJECTS = $(am_libconqserv_la_OBJECTS)
libconqserv_la_LINK = $(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(libconqserv_la_LDFLAGS) $(LDFLAGS) -o $@
#am_libconqserv_la_rpath = -rpath \
#	$(libdir)
am_libconqserv_la_rpath = -rpath \
	$(libdir)
#am_libconqserv_la_rpath = -rpath $(libdir)
libconquest_la_DEPENDENCIES = 
am_libconquest_la_OBJECTS = conqai.lo ratfor.lo conqlb.lo rndlb.lo \
	conqutil.lo conqcm.lo conqsvr42.lo ibuf.lo version.lo conf.lo \
	sem.lo color.lo userauth.lo record.lo packet.lo meta.lo udp.lo \
	rb.lo
libconquest_la_OBJECTS = $(am_libconquest_la_OBJECTS)
libconquest_la_LINK = $(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(libconquest_la_LDFLAGS) $(LDFLAGS) -o $@
#am_libconquest_la_rpath = -rpath \
#	$(libdir)
am_libconquest_la_rpath = -rpath \
	$(libdir)
#am_libconquest_la_rpath = -rpath $(libdir)
libcqsound_la_LIBADD =
am_libcqsound_la_OBJECTS = cqsound.lo
libcqsound_la_OBJECTS = $(am_libcqsound_la_OBJECTS)
libcqsound_la_LINK = $(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(libcqsound_la_LDFLAGS) $(LDFLAGS) -o $@
am_libcqsound_la_rpath = -rpath \
	$(libdir)
#am_libcqsound_la_rpath = -rpath $(libdir)
binPROGRAMS_INSTALL = $(INSTALL_PROGRAM)
libexecPROGRAMS_INSTALL = $(INSTALL_PROGRAM)
PROGRAMS = $(bin_PROGRAMS) $(libexec_PROGRAMS)
am_conqai_OBJECTS = conqai_main.$(OBJEXT)
conqai_OBJECTS = $(am_conqai_OBJECTS)
am__DEPENDENCIES_1 =
conqai_DEPENDENCIES = libconquest.la libconqinit.la \
	$(am__DEPENDENCIES_1)
am_conqdriv_OBJECTS = conqdriv.$(OBJEXT)
conqdriv_OBJECTS = $(am_conqdriv_OBJECTS)
conqdriv_DEPENDENCIES = libconquest.la libconqinit.la \
	$(am__DEPENDENCIES_1)
am_conqinit_OBJECTS = conqinit.$(OBJEXT)
conqinit_OBJECTS = $(am_conqinit_OBJECTS)
conqinit_DEPENDENCIES = libconquest.la libconqinit.la \
	$(am__DEPENDENCIES_1)
am__conqmetad_SOURCES_DIST = conqmetad.c meta.h tcpwrap.h tcpwrap.c
am__objects_1 =
am__objects_2 = tcpwrap.$(OBJEXT)
am_conqmetad_OBJECTS = conqmetad.$(OBJEXT) \
	$(am__objects_1)
#am_conqmetad_OBJECTS = conqmetad.$(OBJEXT) $(am__objects_1) \
#	$(am__objects_2)
conqmetad_OBJECTS = $(am_conqmetad_OBJECTS)
conqmetad_DEPENDENCIES = libconquest.la libconqinit.la \
	$(am__DEPENDENCIES_1)
#conqmetad_DEPENDENCIES = libconquest.la libconqinit.la \
#	$(am__DEPENDENCIES_1) $(am__DEPENDENCIES_1) \
#	$(am__DEPENDENCIES_1)
am_conqoper_OBJECTS = conqoper.$(OBJEXT)
conqoper_OBJECTS = $(am_conqoper_OBJECTS)
conqoper_DEPENDENCIES = libUiCU.la libUi.la libconqclnt.la \
	libconquest.la libconqinit.la $(am__DEPENDENCIES_1)
am_conqstrat_OBJECTS = conqstrat-yacc.$(OBJEXT) \
	conqstrat-lex.$(OBJEXT)
conqstrat_OBJECTS = $(am_conqstrat_OBJECTS)
conqstrat_DEPENDENCIES = libconquest.la $(am__DEPENDENCIES_1)
am_conquest_OBJECTS = conquest.$(OBJEXT) conqreplay.$(OBJEXT)
conquest_OBJECTS = $(am_conquest_OBJECTS)
conquest_DEPENDENCIES = libUiCU.la libUi.la libconqclnt.la \
	libconquest.la libconqinit.la $(am__DEPENDENCIES_1)
am__conquestd_SOURCES_DIST = conquestd.c c_defs.h defs.h conqdef.h \
	conqcom.h context.h conqnet.h tcpwrap.h tcpwrap.c
am_conquestd_OBJECTS = conquestd.$(OBJEXT) \
	$(am__objects_1)
#am_conquestd_OBJECTS = conquestd.$(OBJEXT) $(am__objects_1) \
#	$(am__objects_2)
conquestd_OBJECTS = $(am_conquestd_OBJECTS)
conquestd_DEPENDENCIES = libconqserv.la libconquest.la \
	libconqinit.la $(am__DEPENDENCIES_1)
#conquestd_DEPENDENCIES = libconqserv.la libconquest.la \
#	libconqinit.la $(am__DEPENDENCIES_1) \
#	$(am__DEPENDENCIES_1) $(am__DEPENDENCIES_1)
am__conquestgl_SOURCES_DIST = conquestgl.c c_defs.h defs.h conqdef.h \
	conqcom.h context.h icon.rc
am_conquestgl_OBJECTS = conquestgl.$(OBJEXT)
#am_conquestgl_OBJECTS = conquestgl.$(OBJEXT) \
#	icon.$(OBJEXT)
conquestgl_OBJECTS = $(am_conquestgl_OBJECTS)
am__DEPENDENCIES_2 = $(am__DEPENDENCIES_1)
#am__DEPENDENCIES_2 = $(am__DEPENDENCIES_1)
conquestgl_DEPENDENCIES = libUiGL.la libUi.la libconqclnt.la \
	libconquest.la libcqsound.la libconqinit.la \
	$(am__DEPENDENCIES_2) $(am__DEPENDENCIES_1)
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) \
	$(LDFLAGS) -o $@
LEXCOMPILE = $(LEX) $(LFLAGS) $(AM_LFLAGS)
LTLEXCOMPILE = $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=compile $(LEX) $(LFLAGS) $(AM_LFLAGS)
YLWRAP = $(top_srcdir)/ylwrap
YACCCOMPILE = $(YACC) $(YFLAGS) $(AM_YFLAGS)
LTYACCCOMPILE = $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=compile $(YACC) $(YFLAGS) $(AM_YFLAGS)
SOURCES = $(libUi_la_SOURCES) $(libUiCU_la_SOURCES) \
	$(libUiGL_la_SOURCES) $(libconqclnt_la_SOURCES) \
	$(libconqinit_la_SOURCES) $(libconqserv_la_SOURCES) \
	$(libconquest_la_SOURCES) $(libcqsound_la_SOURCES) \
	$(conqai_SOURCES) $(conqdriv_SOURCES) $(conqinit_SOURCES) \
	$(conqmetad_SOURCES) $(conqoper_SOURCES) $(conqstrat_SOURCES) \
	$(conquest_SOURCES) $(conquestd_SOURCES) $(conquestgl_SOURCES)
DIST_SOURCES = $(libUi_la_SOURCES) $(libUiCU_la_SOURCES) \
	$(libUiGL_la_SOURCES) $(libconqclnt_la_SOURCES) \
	$(libconqinit_la_SOURCES) $(libconqserv_la_SOURCES) \
	$(libconquest_la_SOURCES) $(libcqsound_la_SOURCES) \
	$(conqai_SOURCES) $(conqdriv_SOURCES) $(conqinit_SOURCES) \
	$(am__conqmetad_SOURCES_DIST) $(conqoper_SOURCES) \
	$(conqstrat_SOURCES) $(conquest_SOURCES) \
	$(am__conquestd_SOURCES_DIST) $(am__conquestgl_SOURCES_DIST)
man6dir = $(mandir)/man6
NROFF = nroff
MANS = $(man6_MANS)
sysconfDATA_INSTALL = $(INSTALL_DATA)
DATA = $(sysconf_DATA)
ETAGS = etags
CTAGS = ctags
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  { test ! -d $(distdir) \
    || { find $(distdir) -type d ! -perm -200 -exec chmod u+w {} ';' \
         && rm -fr $(distdir); }; }
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
distuninstallcheck_listfiles = find . -type f -print
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /root/conquest/missing --run aclocal-1.10
AMTAR = ${SHELL} /root/conquest/missing --run tar
AR = ar
AUTOCONF = ${SHELL} /root/conquest/missing --run autoconf
AUTOHEADER = ${SHELL} /root/conquest/missing --run autoheader
AUTOMAKE = ${SHELL} /root/conquest/missing --run automake-1.10
AWK = mawk
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2 -D__NO_MATH_INLINES -Wall -fno-builtin -DNDEBUG -DHAVE_SDL=1 -I/usr/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT -DHAVE_SDL_MIXER=1 $(SDL_CFLAGS)
CONQGROUP = conquest
CONQ_CFLAGS = -g -O2 -D__NO_MATH_INLINES -Wall -fno-builtin -DNDEBUG -DHAVE_SDL=1 -I/usr/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT -DHAVE_SDL_MIXER=1
CPP = gcc -E
CPPFLAGS = 
CXX = g++
CXXCPP = g++ -E
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -g -O2
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
DSYMUTIL = 
ECHO = echo
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /bin/grep -E
EXEEXT = 
F77 = 
FFLAGS = 
GREP = /bin/grep
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LDFLAGS = 
LEX = flex
LEXLIB = -lfl
LEX_OUTPUT_ROOT = lex.yy
LIBOBJS = 
LIBS = -lSDL_mixer -lz -lcurses -lm  -lcrypt
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LN_S = ln -s
LTLIBOBJS = 
MAKEINFO = ${SHELL} /root/conquest/missing --run makeinfo
MKDIR_P = /bin/mkdir -p
NMEDIT = 
NSLLIB = -lnsl
OBJEXT = o
PACKAGE = conquest
PACKAGE_BUGREPORT = jon@radscan.com
PACKAGE_NAME = conquest
PACKAGE_STRING = conquest 8
PACKAGE_TARNAME = conquest
PACKAGE_VERSION = 8
PATH_SEPARATOR = :
RANLIB = ranlib
SDL_CFLAGS = -I/usr/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT
SDL_CONFIG = /usr/bin/sdl-config
SDL_LIBS = -L/usr/lib/x86_64-linux-gnu -lSDL
SED = /bin/sed
SET_MAKE = 
SHELL = /bin/bash
STRIP = strip
TCPWLIB = 
VERSION = 8
XMKMF = 
X_CFLAGS = 
X_EXTRA_LIBS = 
X_LIBS = 
X_PRE_LIBS =  -lSM -lICE
YACC = bison -y
YFLAGS = 
abs_builddir = /root/conquest
abs_srcdir = /root/conquest
abs_top_builddir = /root/conquest
abs_top_srcdir = /root/conquest
ac_ct_CC = gcc
ac_ct_CXX = g++
ac_ct_F77 = 
am__include = include
am__leading_dot = .
am__quote = 
am__tar = ${AMTAR} chof - "$$tardir"
am__untar = ${AMTAR} xf -
bindir = ${exec_prefix}/bin
build = x86_64-unknown-linux-gnu
build_alias = 
build_cpu = x86_64
build_os = linux-gnu
build_vendor = unknown
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host = x86_64-unknown-linux-gnu
host_alias = 
host_cpu = x86_64
host_os = linux-gnu
host_vendor = unknown
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = $(SHELL) /root/conquest/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = /bin/mkdir -p
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /sbbs/doors/conquest
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target = x86_64-unknown-linux-gnu
target_alias = 
target_cpu = x86_64
target_os = linux-gnu
target_vendor = unknown
top_build_prefix = 
top_builddir = .
top_srcdir = .
AUTOMAKE_OPTIONS = foreign
ACLOCAL_AMFLAGS = -I m4 --install
CONQLOCALSTATEDIR = ${prefix}/var/conquest
CONQLIBEXECDIR = ${exec_prefix}/libexec
CONQDATADIR = ${datarootdir}
CONQSYSCONFDIR = ${prefix}/etc
CONQIMGDIR = $(CONQDATADIR)/img
CONQSNDDIR = $(CONQDATADIR)/sound
CONQDOCDIR = $(CONQDATADIR)/doc/conquest
TEXTURESRC = $(DESTDIR)$(CONQSYSCONFDIR)/texturesrc
CONQINITRC = $(DESTDIR)$(CONQSYSCONFDIR)/conqinitrc
SOUNDRC = $(DESTDIR)$(CONQSYSCONFDIR)/soundrc
CONQDOCS = HISTORY README CONQINIT.TXT conqrule conqrule.easy
IMAGES = img/*.tga img/*.txf
SOUNDS = sound/*.ogg 
TRC = *.trc
SRC = *.src
TCPW_H = tcpwrap.h
TCPW_C = tcpwrap.c
man6_MANS = conqdriv.man conqmetad.man conqoper.man conquest.man \
	conquestd.man conqai.man conqstrat.man \
	conqinit.man conquestgl.man

#-lwsock32 
XLIBS =   -lglut -lGL -lGLU -lXt $(SDL_LIBS)  -lSM -lICE -lXext -lXi -lX11 -lXmu  
#XLIBS = -lfreeglut -lopengl32 -lglu32 $(SDL_LIBS) -lws2_32 
INCLUDES = -DCONQUEST_GROUP=\"$(CONQGROUP)\" \
	-DCONQSTATE=\"$(CONQLOCALSTATEDIR)\" -DCONQLIBEXEC=\"$(CONQLIBEXECDIR)\" \
	-DCONQSHARE=\"$(CONQDATADIR)\" -DCONQETC=\"$(CONQSYSCONFDIR)\" \
	-DCONQDOCDIR=\"$(CONQDATADIR)\" \
	

AM_YFLAGS = -d
#lib_LTLIBRARIES = libconquest.la libconqclnt.la libconqserv.la \
#	libconqinit.la libUi.la libUiCU.la

lib_LTLIBRARIES = libconquest.la libconqclnt.la libconqserv.la \
	libconqinit.la libUi.la libUiGL.la libcqsound.la

#lib_LTLIBRARIES = libconquest.la libconqclnt.la libconqserv.la \
#	libconqinit.la libUi.la libUiGL.la libcqsound.la

libconquest_la_SOURCES = conqai.c ratfor.c  \
	conqlb.h conqlb.c rndlb.c conqutil.c conqutil.h conqcm.c \
	conqsvr42.c ibuf.c version.c conf.c sem.c color.c \
	userauth.c record.c color.h user.h shiptype.h \
	ship.h planet.h team.h msg.h doomsday.h driver.h conqinfo.h \
	history.h robot.h global.h torp.h ibuf.h conf.h  display.h \
	protocol.h packet.h packet.c userauth.h meta.c meta.h udp.c udp.h \
	rb.h rb.c

libconquest_la_LIBADD = 
libconquest_la_LDFLAGS = -version-info 1:0:0
libconqclnt_la_SOURCES = client.c client.h clientlb.c clientlb.h \
	playback.h playback.c

libconqclnt_la_LDFLAGS = -version-info 1:0:0
libconqserv_la_SOURCES = servauth.c server.c servauth.h server.h serverpkt.c \
	serverpkt.h servercmd.h servercmd.c

libconqserv_la_LDFLAGS = -version-info 1:0:0
libUi_la_SOURCES = ui.h uimisc.c 
libUi_la_LDFLAGS = -version-info 1:0:0
libUiGL_la_SOURCES = GL.c texfont.c glfont.c glfont.h \
	glmisc.c glmisc.h nConsvr.c nConsvr.h nMeta.h nMeta.c cqkeys.h \
        prm.h prm.c nAuth.h nAuth.c nWelcome.h nWelcome.c nMenu.h nMenu.c \
	nPlay.h nPlay.c nCP.h nCP.c nDead.h nDead.c nCPHelp.h nCPHelp.c \
	nShipl.h nShipl.c node.h node.c nPlanetl.h nPlanetl.c nTeaml.h \
	nTeaml.c nUserl.h nUserl.c nHistl.h nHistl.c cprintf.h glcprintf.c \
	gldisplay.h gldisplay.c disputil.h render.h render.c \
	nPlayBMenu.h nPlayBMenu.c nPlayB.h nPlayB.c nPlayBHelp.h \
	nPlayBHelp.c nOptions.h nOptions.c colorGL.c ui.h anim.c anim.h \
	GL.h hud.h hud.c blinker.h blinker.c

libUiGL_la_LDFLAGS = -version-info 1:0:0
libUiCU_la_SOURCES = display.c cprintf.h cprintf.c disputil.h colorCU.c \
	cd2lb.h cd2lb.c iolb.h iolb.c cumisc.h cumisc.c cuclient.h \
	cuclient.c options.h options.c clntauth.c ui.h display.h 

libUiCU_la_LDFLAGS = -version-info 1:0:0
libconqinit_la_SOURCES = conqinit-yacc.y conqinit-lex.l conqinit.h initdata.h planinit.c
libconqinit_la_LDFLAGS = -version-info 1:0:0
libcqsound_la_SOURCES = cqsound.c cqsound.h
libcqsound_la_LDFLAGS = -version-info 1:0:0
conquest_SOURCES = conquest.c c_defs.h defs.h conqdef.h conqcom.h context.h \
	conqreplay.c

conquest_LDADD = libUiCU.la libUi.la libconqclnt.la libconquest.la libconqinit.la $(LEXLIB) $(YACCLIB)
conquestgl_SOURCES = conquestgl.c c_defs.h defs.h conqdef.h conqcom.h context.h
#conquestgl_SOURCES = conquestgl.c c_defs.h defs.h conqdef.h conqcom.h \
#	context.h icon.rc

conquestgl_LDADD = libUiGL.la libUi.la libconqclnt.la libconquest.la libcqsound.la libconqinit.la $(XLIBS) $(LEXLIB) $(YACCLIB)
conquestd_SOURCES = conquestd.c c_defs.h defs.h conqdef.h conqcom.h \
	context.h conqnet.h $(TCPW_H) 

#conquestd_SOURCES = conquestd.c c_defs.h defs.h conqdef.h conqcom.h \
#	context.h conqnet.h $(TCPW_H) $(TCPW_C) 

conquestd_LDADD = libconqserv.la libconquest.la libconqinit.la $(LEXLIB) $(YACCLIB)
#conquestd_LDADD = libconqserv.la libconquest.la libconqinit.la $(LEXLIB) $(YACCLIB) $(TCPWLIB) $(NSLLIB)
conqai_SOURCES = conqai_main.c c_defs.h defs.h conqdef.h conqcom.h \
                 context.h conqdata.h

conqai_LDADD = libconquest.la libconqinit.la  $(LEXLIB) $(YACCLIB)
conqoper_SOURCES = conqoper.c c_defs.h defs.h conqdef.h conqcom.h context.h 
conqoper_LDADD = libUiCU.la libUi.la libconqclnt.la libconquest.la libconqinit.la $(LEXLIB) $(YACCLIB) 
conqdriv_SOURCES = conqdriv.c c_defs.h defs.h conqdef.h conqcom.h context.h
conqdriv_LDADD = libconquest.la libconqinit.la $(LEXLIB) $(YACCLIB)
conqstrat_SOURCES = conqstrat-yacc.y conqstrat-lex.l conqstrat.h
conqstrat_LDADD = libconquest.la $(LEXLIB) $(YACCLIB) 
conqinit_SOURCES = conqinit.c conqinit.h 
conqinit_LDADD = libconquest.la libconqinit.la $(LEXLIB) $(YACCLIB) 
conqmetad_SOURCES = conqmetad.c meta.h $(TCPW_H) 
#conqmetad_SOURCES = conqmetad.c meta.h $(TCPW_H) $(TCPW_C) 
conqmetad_LDADD = libconquest.la libconqinit.la $(LEXLIB) $(YACCLIB) 
#conqmetad_LDADD = libconquest.la libconqinit.la $(LEXLIB) $(YACCLIB) $(TCPWLIB) $(NSLLIB)

# we install conqinitrc in the intall-exec-hook, so that we only install
#  conqinitrc if it does not already exist.
sysconf_DATA = texturesrc soundrc $(TRC) #$(SRC)
EXTRA_DIST = $(man6_MANS)
all: config.h
	$(MAKE) $(AM_MAKEFLAGS) all-am

.SUFFIXES:
.SUFFIXES: .c .l .lo .o .obj .rc .y
am--refresh:
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --foreign '; \
	      cd $(srcdir) && $(AUTOMAKE) --foreign  \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign  Makefile'; \
	cd $(top_srcdir) && \
	  $(AUTOMAKE) --foreign  Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	cd $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	cd $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)

config.h: stamp-h1
	@if test ! -f $@; then \
	  rm -f stamp-h1; \
	  $(MAKE) $(AM_MAKEFLAGS) stamp-h1; \
	else :; fi

stamp-h1: $(srcdir)/config.h.in $(top_builddir)/config.status
	@rm -f stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status config.h
$(srcdir)/config.h.in:  $(am__configure_deps) 
	cd $(top_srcdir) && $(AUTOHEADER)
	rm -f stamp-h1
	touch $@

distclean-hdr:
	-rm -f config.h stamp-h1
install-libLTLIBRARIES: $(lib_LTLIBRARIES)
	@$(NORMAL_INSTALL)
	test -z "$(libdir)" || $(MKDIR_P) "$(DESTDIR)$(libdir)"
	@list='$(lib_LTLIBRARIES)'; for p in $$list; do \
	  if test -f $$p; then \
	    f=$(am__strip_dir) \
	    echo " $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(libLTLIBRARIES_INSTALL) $(INSTALL_STRIP_FLAG) '$$p' '$(DESTDIR)$(libdir)/$$f'"; \
	    $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(libLTLIBRARIES_INSTALL) $(INSTALL_STRIP_FLAG) "$$p" "$(DESTDIR)$(libdir)/$$f"; \
	  else :; fi; \
	done

uninstall-libLTLIBRARIES:
	@$(NORMAL_UNINSTALL)
	@list='$(lib_LTLIBRARIES)'; for p in $$list; do \
	  p=$(am__strip_dir) \
	  echo " $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=uninstall rm -f '$(DESTDIR)$(libdir)/$$p'"; \
	  $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=uninstall rm -f "$(DESTDIR)$(libdir)/$$p"; \
	done

clean-libLTLIBRARIES:
	-test -z "$(lib_LTLIBRARIES)" || rm -f $(lib_LTLIBRARIES)
	@list='$(lib_LTLIBRARIES)'; for p in $$list; do \
	  dir="`echo $$p | sed -e 's|/[^/]*$$||'`"; \
	  test "$$dir" != "$$p" || dir=.; \
	  echo "rm -f \"$${dir}/so_locations\""; \
	  rm -f "$${dir}/so_locations"; \
	done
libUi.la: $(libUi_la_OBJECTS) $(libUi_la_DEPENDENCIES) 
	$(libUi_la_LINK) $(am_libUi_la_rpath) $(libUi_la_OBJECTS) $(libUi_la_LIBADD) $(LIBS)
libUiCU.la: $(libUiCU_la_OBJECTS) $(libUiCU_la_DEPENDENCIES) 
	$(libUiCU_la_LINK) $(am_libUiCU_la_rpath) $(libUiCU_la_OBJECTS) $(libUiCU_la_LIBADD) $(LIBS)
libUiGL.la: $(libUiGL_la_OBJECTS) $(libUiGL_la_DEPENDENCIES) 
	$(libUiGL_la_LINK) $(am_libUiGL_la_rpath) $(libUiGL_la_OBJECTS) $(libUiGL_la_LIBADD) $(LIBS)
libconqclnt.la: $(libconqclnt_la_OBJECTS) $(libconqclnt_la_DEPENDENCIES) 
	$(libconqclnt_la_LINK) $(am_libconqclnt_la_rpath) $(libconqclnt_la_OBJECTS) $(libconqclnt_la_LIBADD) $(LIBS)
conqinit-yacc.h: conqinit-yacc.c
	@if test ! -f $@; then \
	  rm -f conqinit-yacc.c; \
	  $(MAKE) $(AM_MAKEFLAGS) conqinit-yacc.c; \
	else :; fi
libconqinit.la: $(libconqinit_la_OBJECTS) $(libconqinit_la_DEPENDENCIES) 
	$(libconqinit_la_LINK) $(am_libconqinit_la_rpath) $(libconqinit_la_OBJECTS) $(libconqinit_la_LIBADD) $(LIBS)
libconqserv.la: $(libconqserv_la_OBJECTS) $(libconqserv_la_DEPENDENCIES) 
	$(libconqserv_la_LINK) $(am_libconqserv_la_rpath) $(libconqserv_la_OBJECTS) $(libconqserv_la_LIBADD) $(LIBS)
libconquest.la: $(libconquest_la_OBJECTS) $(libconquest_la_DEPENDENCIES) 
	$(libconquest_la_LINK) $(am_libconquest_la_rpath) $(libconquest_la_OBJECTS) $(libconquest_la_LIBADD) $(LIBS)
libcqsound.la: $(libcqsound_la_OBJECTS) $(libcqsound_la_DEPENDENCIES) 
	$(libcqsound_la_LINK) $(am_libcqsound_la_rpath) $(libcqsound_la_OBJECTS) $(libcqsound_la_LIBADD) $(LIBS)
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	test -z "$(bindir)" || $(MKDIR_P) "$(DESTDIR)$(bindir)"
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  p1=`echo $$p|sed 's/$(EXEEXT)$$//'`; \
	  if test -f $$p \
	     || test -f $$p1 \
	  ; then \
	    f=`echo "$$p1" | sed 's,^.*/,,;$(transform);s/$$/$(EXEEXT)/'`; \
	   echo " $(INSTALL_PROGRAM_ENV) $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(binPROGRAMS_INSTALL) '$$p' '$(DESTDIR)$(bindir)/$$f'"; \
	   $(INSTALL_PROGRAM_ENV) $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(binPROGRAMS_INSTALL) "$$p" "$(DESTDIR)$(bindir)/$$f" || exit 1; \
	  else :; fi; \
	done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  f=`echo "$$p" | sed 's,^.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/'`; \
	  echo " rm -f '$(DESTDIR)$(bindir)/$$f'"; \
	  rm -f "$(DESTDIR)$(bindir)/$$f"; \
	done

clean-binPROGRAMS:
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  f=`echo $$p|sed 's/$(EXEEXT)$$//'`; \
	  echo " rm -f $$p $$f"; \
	  rm -f $$p $$f ; \
	done
install-libexecPROGRAMS: $(libexec_PROGRAMS)
	@$(NORMAL_INSTALL)
	test -z "$(libexecdir)" || $(MKDIR_P) "$(DESTDIR)$(libexecdir)"
	@list='$(libexec_PROGRAMS)'; for p in $$list; do \
	  p1=`echo $$p|sed 's/$(EXEEXT)$$//'`; \
	  if test -f $$p \
	     || test -f $$p1 \
	  ; then \
	    f=`echo "$$p1" | sed 's,^.*/,,;$(transform);s/$$/$(EXEEXT)/'`; \
	   echo " $(INSTALL_PROGRAM_ENV) $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(libexecPROGRAMS_INSTALL) '$$p' '$(DESTDIR)$(libexecdir)/$$f'"; \
	   $(INSTALL_PROGRAM_ENV) $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(libexecPROGRAMS_INSTALL) "$$p" "$(DESTDIR)$(libexecdir)/$$f" || exit 1; \
	  else :; fi; \
	done

uninstall-libexecPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(libexec_PROGRAMS)'; for p in $$list; do \
	  f=`echo "$$p" | sed 's,^.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/'`; \
	  echo " rm -f '$(DESTDIR)$(libexecdir)/$$f'"; \
	  rm -f "$(DESTDIR)$(libexecdir)/$$f"; \
	done

clean-libexecPROGRAMS:
	@list='$(libexec_PROGRAMS)'; for p in $$list; do \
	  f=`echo $$p|sed 's/$(EXEEXT)$$//'`; \
	  echo " rm -f $$p $$f"; \
	  rm -f $$p $$f ; \
	done
conqai$(EXEEXT): $(conqai_OBJECTS) $(conqai_DEPENDENCIES) 
	@rm -f conqai$(EXEEXT)
	$(LINK) $(conqai_OBJECTS) $(conqai_LDADD) $(LIBS)
conqdriv$(EXEEXT): $(conqdriv_OBJECTS) $(conqdriv_DEPENDENCIES) 
	@rm -f conqdriv$(EXEEXT)
	$(LINK) $(conqdriv_OBJECTS) $(conqdriv_LDADD) $(LIBS)
conqinit$(EXEEXT): $(conqinit_OBJECTS) $(conqinit_DEPENDENCIES) 
	@rm -f conqinit$(EXEEXT)
	$(LINK) $(conqinit_OBJECTS) $(conqinit_LDADD) $(LIBS)
conqmetad$(EXEEXT): $(conqmetad_OBJECTS) $(conqmetad_DEPENDENCIES) 
	@rm -f conqmetad$(EXEEXT)
	$(LINK) $(conqmetad_OBJECTS) $(conqmetad_LDADD) $(LIBS)
conqoper$(EXEEXT): $(conqoper_OBJECTS) $(conqoper_DEPENDENCIES) 
	@rm -f conqoper$(EXEEXT)
	$(LINK) $(conqoper_OBJECTS) $(conqoper_LDADD) $(LIBS)
conqstrat-yacc.h: conqstrat-yacc.c
	@if test ! -f $@; then \
	  rm -f conqstrat-yacc.c; \
	  $(MAKE) $(AM_MAKEFLAGS) conqstrat-yacc.c; \
	else :; fi
conqstrat$(EXEEXT): $(conqstrat_OBJECTS) $(conqstrat_DEPENDENCIES) 
	@rm -f conqstrat$(EXEEXT)
	$(LINK) $(conqstrat_OBJECTS) $(conqstrat_LDADD) $(LIBS)
conquest$(EXEEXT): $(conquest_OBJECTS) $(conquest_DEPENDENCIES) 
	@rm -f conquest$(EXEEXT)
	$(LINK) $(conquest_OBJECTS) $(conquest_LDADD) $(LIBS)
conquestd$(EXEEXT): $(conquestd_OBJECTS) $(conquestd_DEPENDENCIES) 
	@rm -f conquestd$(EXEEXT)
	$(LINK) $(conquestd_OBJECTS) $(conquestd_LDADD) $(LIBS)
conquestgl$(EXEEXT): $(conquestgl_OBJECTS) $(conquestgl_DEPENDENCIES) 
	@rm -f conquestgl$(EXEEXT)
	$(LINK) $(conquestgl_OBJECTS) $(conquestgl_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/GL.Plo
include ./$(DEPDIR)/anim.Plo
include ./$(DEPDIR)/blinker.Plo
include ./$(DEPDIR)/cd2lb.Plo
include ./$(DEPDIR)/client.Plo
include ./$(DEPDIR)/clientlb.Plo
include ./$(DEPDIR)/clntauth.Plo
include ./$(DEPDIR)/color.Plo
include ./$(DEPDIR)/colorCU.Plo
include ./$(DEPDIR)/colorGL.Plo
include ./$(DEPDIR)/conf.Plo
include ./$(DEPDIR)/conqai.Plo
include ./$(DEPDIR)/conqai_main.Po
include ./$(DEPDIR)/conqcm.Plo
include ./$(DEPDIR)/conqdriv.Po
include ./$(DEPDIR)/conqinit-lex.Plo
include ./$(DEPDIR)/conqinit-yacc.Plo
include ./$(DEPDIR)/conqinit.Po
include ./$(DEPDIR)/conqlb.Plo
include ./$(DEPDIR)/conqmetad.Po
include ./$(DEPDIR)/conqoper.Po
include ./$(DEPDIR)/conqreplay.Po
include ./$(DEPDIR)/conqstrat-lex.Po
include ./$(DEPDIR)/conqstrat-yacc.Po
include ./$(DEPDIR)/conqsvr42.Plo
include ./$(DEPDIR)/conquest.Po
include ./$(DEPDIR)/conquestd.Po
include ./$(DEPDIR)/conquestgl.Po
include ./$(DEPDIR)/conqutil.Plo
include ./$(DEPDIR)/cprintf.Plo
include ./$(DEPDIR)/cqsound.Plo
include ./$(DEPDIR)/cuclient.Plo
include ./$(DEPDIR)/cumisc.Plo
include ./$(DEPDIR)/display.Plo
include ./$(DEPDIR)/glcprintf.Plo
include ./$(DEPDIR)/gldisplay.Plo
include ./$(DEPDIR)/glfont.Plo
include ./$(DEPDIR)/glmisc.Plo
include ./$(DEPDIR)/hud.Plo
include ./$(DEPDIR)/ibuf.Plo
include ./$(DEPDIR)/iolb.Plo
include ./$(DEPDIR)/meta.Plo
include ./$(DEPDIR)/nAuth.Plo
include ./$(DEPDIR)/nCP.Plo
include ./$(DEPDIR)/nCPHelp.Plo
include ./$(DEPDIR)/nConsvr.Plo
include ./$(DEPDIR)/nDead.Plo
include ./$(DEPDIR)/nHistl.Plo
include ./$(DEPDIR)/nMenu.Plo
include ./$(DEPDIR)/nMeta.Plo
include ./$(DEPDIR)/nOptions.Plo
include ./$(DEPDIR)/nPlanetl.Plo
include ./$(DEPDIR)/nPlay.Plo
include ./$(DEPDIR)/nPlayB.Plo
include ./$(DEPDIR)/nPlayBHelp.Plo
include ./$(DEPDIR)/nPlayBMenu.Plo
include ./$(DEPDIR)/nShipl.Plo
include ./$(DEPDIR)/nTeaml.Plo
include ./$(DEPDIR)/nUserl.Plo
include ./$(DEPDIR)/nWelcome.Plo
include ./$(DEPDIR)/node.Plo
include ./$(DEPDIR)/options.Plo
include ./$(DEPDIR)/packet.Plo
include ./$(DEPDIR)/planinit.Plo
include ./$(DEPDIR)/playback.Plo
include ./$(DEPDIR)/prm.Plo
include ./$(DEPDIR)/ratfor.Plo
include ./$(DEPDIR)/rb.Plo
include ./$(DEPDIR)/record.Plo
include ./$(DEPDIR)/render.Plo
include ./$(DEPDIR)/rndlb.Plo
include ./$(DEPDIR)/sem.Plo
include ./$(DEPDIR)/servauth.Plo
include ./$(DEPDIR)/server.Plo
include ./$(DEPDIR)/servercmd.Plo
include ./$(DEPDIR)/serverpkt.Plo
include ./$(DEPDIR)/tcpwrap.Po
include ./$(DEPDIR)/texfont.Plo
include ./$(DEPDIR)/udp.Plo
include ./$(DEPDIR)/uimisc.Plo
include ./$(DEPDIR)/userauth.Plo
include ./$(DEPDIR)/version.Plo

.c.o:
	$(COMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	mv -f $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(COMPILE) -c $<

.c.obj:
	$(COMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ `$(CYGPATH_W) '$<'`
	mv -f $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(COMPILE) -c `$(CYGPATH_W) '$<'`

.c.lo:
	$(LTCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	mv -f $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Plo
#	source='$<' object='$@' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LTCOMPILE) -c -o $@ $<

.l.c:
	$(am__skiplex) $(SHELL) $(YLWRAP) $< $(LEX_OUTPUT_ROOT).c $@ -- $(LEXCOMPILE)

.y.c:
	$(am__skipyacc) $(SHELL) $(YLWRAP) $< y.tab.c $@ y.tab.h $*.h y.output $*.output -- $(YACCCOMPILE)

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:
	-rm -f libtool
install-man6: $(man6_MANS) $(man_MANS)
	@$(NORMAL_INSTALL)
	test -z "$(man6dir)" || $(MKDIR_P) "$(DESTDIR)$(man6dir)"
	@list='$(man6_MANS) $(dist_man6_MANS) $(nodist_man6_MANS)'; \
	l2='$(man_MANS) $(dist_man_MANS) $(nodist_man_MANS)'; \
	for i in $$l2; do \
	  case "$$i" in \
	    *.6*) list="$$list $$i" ;; \
	  esac; \
	done; \
	for i in $$list; do \
	  if test -f $(srcdir)/$$i; then file=$(srcdir)/$$i; \
	  else file=$$i; fi; \
	  ext=`echo $$i | sed -e 's/^.*\\.//'`; \
	  case "$$ext" in \
	    6*) ;; \
	    *) ext='6' ;; \
	  esac; \
	  inst=`echo $$i | sed -e 's/\\.[0-9a-z]*$$//'`; \
	  inst=`echo $$inst | sed -e 's/^.*\///'`; \
	  inst=`echo $$inst | sed '$(transform)'`.$$ext; \
	  echo " $(INSTALL_DATA) '$$file' '$(DESTDIR)$(man6dir)/$$inst'"; \
	  $(INSTALL_DATA) "$$file" "$(DESTDIR)$(man6dir)/$$inst"; \
	done
uninstall-man6:
	@$(NORMAL_UNINSTALL)
	@list='$(man6_MANS) $(dist_man6_MANS) $(nodist_man6_MANS)'; \
	l2='$(man_MANS) $(dist_man_MANS) $(nodist_man_MANS)'; \
	for i in $$l2; do \
	  case "$$i" in \
	    *.6*) list="$$list $$i" ;; \
	  esac; \
	done; \
	for i in $$list; do \
	  ext=`echo $$i | sed -e 's/^.*\\.//'`; \
	  case "$$ext" in \
	    6*) ;; \
	    *) ext='6' ;; \
	  esac; \
	  inst=`echo $$i | sed -e 's/\\.[0-9a-z]*$$//'`; \
	  inst=`echo $$inst | sed -e 's/^.*\///'`; \
	  inst=`echo $$inst | sed '$(transform)'`.$$ext; \
	  echo " rm -f '$(DESTDIR)$(man6dir)/$$inst'"; \
	  rm -f "$(DESTDIR)$(man6dir)/$$inst"; \
	done
install-sysconfDATA: $(sysconf_DATA)
	@$(NORMAL_INSTALL)
	test -z "$(sysconfdir)" || $(MKDIR_P) "$(DESTDIR)$(sysconfdir)"
	@list='$(sysconf_DATA)'; for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  f=$(am__strip_dir) \
	  echo " $(sysconfDATA_INSTALL) '$$d$$p' '$(DESTDIR)$(sysconfdir)/$$f'"; \
	  $(sysconfDATA_INSTALL) "$$d$$p" "$(DESTDIR)$(sysconfdir)/$$f"; \
	done

uninstall-sysconfDATA:
	@$(NORMAL_UNINSTALL)
	@list='$(sysconf_DATA)'; for p in $$list; do \
	  f=$(am__strip_dir) \
	  echo " rm -f '$(DESTDIR)$(sysconfdir)/$$f'"; \
	  rm -f "$(DESTDIR)$(sysconfdir)/$$f"; \
	done

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonemtpy = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	mkid -fID $$unique
tags: TAGS

TAGS:  $(HEADERS) $(SOURCES) config.h.in $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS) config.h.in $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	if test -z "$(ETAGS_ARGS)$$tags$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	    $$tags $$unique; \
	fi
ctags: CTAGS
CTAGS:  $(HEADERS) $(SOURCES) config.h.in $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	list='$(SOURCES) $(HEADERS) config.h.in $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	test -z "$(CTAGS_ARGS)$$tags$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$tags $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && cd $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) $$here

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d $(distdir) || mkdir $(distdir)
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -pR $(srcdir)/$$file $(distdir)$$dir || exit 1; \
	    fi; \
	    cp -pR $$d/$$file $(distdir)$$dir || exit 1; \
	  else \
	    test -f $(distdir)/$$file \
	    || cp -p $$d/$$file $(distdir)/$$file \
	    || exit 1; \
	  fi; \
	done
	-find $(distdir) -type d ! -perm -777 -exec chmod a+rwx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r $(distdir)
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | bzip2 -9 -c >$(distdir).tar.bz2
	$(am__remove_distdir)

dist-lzma: distdir
	tardir=$(distdir) && $(am__tar) | lzma -9 -c >$(distdir).tar.lzma
	$(am__remove_distdir)

dist-tarZ: distdir
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__remove_distdir)

dist-shar: distdir
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__remove_distdir)

dist dist-all: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gunzip -c $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bunzip2 -c $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lzma*) \
	  unlzma -c $(distdir).tar.lzma | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gunzip -c $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir); chmod a+w $(distdir)
	mkdir $(distdir)/_build
	mkdir $(distdir)/_inst
	chmod a-w $(distdir)
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && cd $(distdir)/_build \
	  && ../configure --srcdir=.. --prefix="$$dc_install_base" \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck
	$(am__remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@cd $(distuninstallcheck_dir) \
	&& test `$(distuninstallcheck_listfiles) | wc -l` -le 1 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-am
all-am: Makefile $(LTLIBRARIES) $(PROGRAMS) $(MANS) $(DATA) config.h
install-binPROGRAMS: install-libLTLIBRARIES

installdirs:
	for dir in "$(DESTDIR)$(libdir)" "$(DESTDIR)$(bindir)" "$(DESTDIR)$(libexecdir)" "$(DESTDIR)$(man6dir)" "$(DESTDIR)$(sysconfdir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
	-rm -f conqinit-lex.c
	-rm -f conqinit-yacc.c
	-rm -f conqinit-yacc.h
	-rm -f conqstrat-lex.c
	-rm -f conqstrat-yacc.c
	-rm -f conqstrat-yacc.h
clean: clean-am

clean-am: clean-binPROGRAMS clean-generic clean-libLTLIBRARIES \
	clean-libexecPROGRAMS clean-libtool mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-hdr distclean-libtool distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

info: info-am

info-am:

install-data-am: install-man

install-dvi: install-dvi-am

install-exec-am: install-binPROGRAMS install-libLTLIBRARIES \
	install-libexecPROGRAMS install-sysconfDATA
	@$(NORMAL_INSTALL)
	$(MAKE) $(AM_MAKEFLAGS) install-exec-hook

install-html: install-html-am

install-info: install-info-am

install-man: install-man6

install-pdf: install-pdf-am

install-ps: install-ps-am

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-binPROGRAMS uninstall-libLTLIBRARIES \
	uninstall-libexecPROGRAMS uninstall-man uninstall-sysconfDATA

uninstall-man: uninstall-man6

.MAKE: install-am install-exec-am install-strip

.PHONY: CTAGS GTAGS all all-am am--refresh check check-am clean \
	clean-binPROGRAMS clean-generic clean-libLTLIBRARIES \
	clean-libexecPROGRAMS clean-libtool ctags dist dist-all \
	dist-bzip2 dist-gzip dist-lzma dist-shar dist-tarZ dist-zip \
	distcheck distclean distclean-compile distclean-generic \
	distclean-hdr distclean-libtool distclean-tags distcleancheck \
	distdir distuninstallcheck dvi dvi-am html html-am info \
	info-am install install-am install-binPROGRAMS install-data \
	install-data-am install-dvi install-dvi-am install-exec \
	install-exec-am install-exec-hook install-html install-html-am \
	install-info install-info-am install-libLTLIBRARIES \
	install-libexecPROGRAMS install-man install-man6 install-pdf \
	install-pdf-am install-ps install-ps-am install-strip \
	install-sysconfDATA installcheck installcheck-am installdirs \
	maintainer-clean maintainer-clean-generic mostlyclean \
	mostlyclean-compile mostlyclean-generic mostlyclean-libtool \
	pdf pdf-am ps ps-am tags uninstall uninstall-am \
	uninstall-binPROGRAMS uninstall-libLTLIBRARIES \
	uninstall-libexecPROGRAMS uninstall-man uninstall-man6 \
	uninstall-sysconfDATA


# User defineable options

.rc.o:
	x86_64-unknown-linux-gnu-windres $^ -o $@

install-exec-hook:
	$(mkinstalldirs) -m 755 $(DESTDIR) $(DESTDIR)$(localstatedir) \
		$(DESTDIR)$(CONQSYSCONFDIR) \
		$(DESTDIR)$(CONQLOCALSTATEDIR) \
		$(DESTDIR)$(CONQDATADIR) \
		$(DESTDIR)$(CONQDATADIR)/doc \
		$(DESTDIR)$(CONQDATADIR)/doc/conquest \
		$(DESTDIR)$(CONQIMGDIR) \
		$(DESTDIR)$(CONQSNDDIR) \
		$(DESTDIR)$(bindir) \
		$(DESTDIR)$(libexecdir) \
		$(DESTDIR)$(libdir) \
		$(DESTDIR)/$(mandir) \
		$(DESTDIR)/$(mandir)/man6 
	chmod 775 $(DESTDIR)$(CONQLOCALSTATEDIR) 
	chgrp $(CONQGROUP) $(DESTDIR)$(CONQLOCALSTATEDIR)
	cp -f $(IMAGES) $(DESTDIR)$(CONQIMGDIR)/
	chmod 644 $(DESTDIR)$(CONQIMGDIR)/*.tga $(DESTDIR)$(CONQIMGDIR)/*.txf
	cp -f $(SOUNDS) $(DESTDIR)$(CONQSNDDIR)/
	chmod 644 $(DESTDIR)$(CONQSNDDIR)/*.ogg 
	cp -f $(CONQDOCS) $(DESTDIR)$(CONQDOCDIR)/
	chmod 644 $(DESTDIR)$(CONQDOCDIR)/*
	if [ ! -f $(DESTDIR)$(CONQSYSCONFDIR)/conqinitrc ] ; \
	then \
		cp conqinitrc $(DESTDIR)$(CONQSYSCONFDIR)/conqinitrc; \
	fi
	chgrp $(CONQGROUP) $(TEXTURESRC) $(CONQINITRC) $(SOUNDRC) 
	chmod 664 $(TEXTURESRC) $(CONQINITRC) $(SOUNDRC)
	chgrp $(CONQGROUP) $(DESTDIR)$(bindir)/conqoper$(EXEEXT) \
		$(DESTDIR)$(libexecdir)/conqdriv$(EXEEXT) \
		$(DESTDIR)$(bindir)/conquestd$(EXEEXT)
	chmod g+s $(DESTDIR)$(bindir)/conqoper$(EXEEXT) \
		$(DESTDIR)$(libexecdir)/conqdriv$(EXEEXT) \
		$(DESTDIR)$(bindir)/conquestd$(EXEEXT)
	-$(bindir)/conqoper$(EXEEXT) -C
	chmod 775 $(DESTDIR)$(CONQLOCALSTATEDIR)
	-chown root:$(CONQGROUP) $(DESTDIR)$(CONQLOCALSTATEDIR)
# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
